[programs.localnet]
staking = "programs/staking"
rewards = "programs/rewards"
governance = "programs/governance"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf"
