name: Anchor CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked

      - name: Build
        run: anchor build

      - name: Test
        run: anchor test